# Generated by Django 4.1.6 on 2023-07-09 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('composition', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('count', models.IntegerField()),
                ('warehouse_count', models.IntegerField(blank=True, null=True)),
                ('original_count', models.CharField(max_length=255)),
                ('weight', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('expired_date', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('price1', models.FloatField()),
                ('price2', models.FloatField()),
                ('seria', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
