# Generated by Django 4.1.6 on 2024-01-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
    ]
