# Generated by Django 4.1.6 on 2024-03-10 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_user', '0002_mobileapp_version1'),
    ]

    # operations = [
    #     migrations.DeleteModel(
    #         name='MobileApp',
    #     ),
    # ]
