# Generated by Django 4.1.6 on 2024-03-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_user', '0003_delete_mobileapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appmobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=15, verbose_name='Version')),
                ('app', models.FileField(upload_to='app')),
            ],
            options={
                'verbose_name': 'Mobile APP',
            },
        ),
        # migrations.DeleteModel(
        #     name='MobileApp',
        # ),
    ]
