# Generated by Django 4.1.6 on 2024-03-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_user', '0004_appmobile_delete_mobileapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilelocation',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
