# Generated by Django 4.1.6 on 2023-03-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_user', '0059_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
            ],
        ),
    ]
