# Generated by Django 4.1.6 on 2023-03-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_user', '0060_orderexcel'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderexcel',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
