# Generated by Django 4.1.6 on 2023-04-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_user', '0063_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
