# Generated by Django 4.1.6 on 2023-04-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_user', '0064_income_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
