# Generated by Django 4.1.6 on 2023-04-20 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_user', '0065_hospital_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='address',
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_city', to='apps_user.city')),
            ],
        ),
        migrations.CreateModel(
            name='CheckMp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('preparation', models.IntegerField()),
                ('communication', models.IntegerField()),
                ('the_need', models.IntegerField()),
                ('presentation', models.IntegerField()),
                ('protest', models.IntegerField()),
                ('agreement', models.IntegerField()),
                ('analysis', models.IntegerField()),
                ('is_pharmacy', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_city', to='apps_user.city')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_mp', to='apps_user.doctor')),
                ('lpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_mp', to='apps_user.hospital')),
                ('mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mp_user', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_mp', to='apps_user.pharmacy')),
            ],
        ),
    ]
