# Generated by Django 4.1.6 on 2023-07-08 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_user', '0066_remove_hospital_address_pharmacy_checkmp'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_city', to=settings.AUTH_USER_MODEL),
        ),
    ]
