# Generated by Django 4.1.6 on 2024-02-01 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('apps_user', '0069_version_checkmp_created_at_checkmp_district_and_more'),
        ('product', '0002_product_image_mobile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        
    ]
