# Generated by Django 4.1.6 on 2024-01-17 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_user', '0068_version_checkmp_created_at_checkmp_district_and_more'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductResidue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='company_director_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_director_phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_provider_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_provider_phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district_order', to='apps_user.district'),
        ),
        migrations.CreateModel(
            name='ProductResidueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('company_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='order.companyproduct')),
                ('product_residue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.productresidue')),
            ],
        ),
        migrations.AddField(
            model_name='companyproduct',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.company'),
        ),
        migrations.AddField(
            model_name='companyproduct',
            name='product',
            field=models.ManyToManyField(related_name='order_products', through='order.ProductResidueItem', to='order.productresidue'),
        ),
    ]
