# Generated by Django 4.1.6 on 2024-01-17 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0002_companyproduct_productresidue_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps_user', '0068_version_checkmp_created_at_checkmp_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalVizitResidueExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('path', models.FileField(upload_to='hospital')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalVizitOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=256)),
                ('aknel_gel', models.CharField(blank=True, max_length=256, null=True)),
                ('astarakson_1125', models.CharField(blank=True, max_length=256, null=True)),
                ('astarakson_562', models.CharField(blank=True, max_length=256, null=True)),
                ('astaryus', models.CharField(blank=True, max_length=256, null=True)),
                ('intrizol', models.CharField(blank=True, max_length=256, null=True)),
                ('livomed_tab', models.CharField(blank=True, max_length=256, null=True)),
                ('livomed_sirop', models.CharField(blank=True, max_length=256, null=True)),
                ('renum_cap', models.CharField(blank=True, max_length=256, null=True)),
                ('stresson_cap', models.CharField(blank=True, max_length=256, null=True)),
                ('tavamed', models.CharField(blank=True, max_length=256, null=True)),
                ('x_payls_maz', models.CharField(blank=True, max_length=256, null=True)),
                ('seprazon', models.CharField(blank=True, max_length=256, null=True)),
                ('entro_d_cap', models.CharField(blank=True, max_length=256, null=True)),
                ('entro_d_sashe', models.CharField(blank=True, max_length=256, null=True)),
                ('lamino_100', models.CharField(blank=True, max_length=256, null=True)),
                ('lamino_200', models.CharField(blank=True, max_length=256, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_company_vizit', to='order.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_hospital_vizit', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_district_vizit', to='apps_user.district')),
            ],
        ),
        migrations.CreateModel(
            name='DoubleVizitExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('file_path', models.FileField(upload_to='double_vizit')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_user.district')),
            ],
        ),
    ]
