# Generated by Django 4.1.6 on 2024-02-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoubleVizitExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('file_path', models.FileField(upload_to='double_vizit')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalVizitOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=256)),
                ('aknel_gel', models.CharField(blank=True, max_length=256, null=True)),
                ('astarakson_1125', models.CharField(blank=True, max_length=256, null=True)),
                ('astarakson_562', models.CharField(blank=True, max_length=256, null=True)),
                ('astaryus', models.CharField(blank=True, max_length=256, null=True)),
                ('intrizol', models.CharField(blank=True, max_length=256, null=True)),
                ('livomed_tab', models.CharField(blank=True, max_length=256, null=True)),
                ('livomed_sirop', models.CharField(blank=True, max_length=256, null=True)),
                ('renum_cap', models.CharField(blank=True, max_length=256, null=True)),
                ('stresson_cap', models.CharField(blank=True, max_length=256, null=True)),
                ('tavamed', models.CharField(blank=True, max_length=256, null=True)),
                ('x_payls_maz', models.CharField(blank=True, max_length=256, null=True)),
                ('seprazon', models.CharField(blank=True, max_length=256, null=True)),
                ('entro_d_cap', models.CharField(blank=True, max_length=256, null=True)),
                ('entro_d_sashe', models.CharField(blank=True, max_length=256, null=True)),
                ('lamino_100', models.CharField(blank=True, max_length=256, null=True)),
                ('lamino_200', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalVizitResidueExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('path', models.FileField(upload_to='hospital')),
            ],
        ),
    ]
