# Generated by Django 4.1.6 on 2024-02-01 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('double_vizit', '0001_initial'),
        ('order', '0002_initial'),
        # ('apps_user', '0069_version_checkmp_created_at_checkmp_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalvizitorder',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_company_vizit', to='order.company'),
        ),
        migrations.AddField(
            model_name='hospitalvizitorder',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_hospital_vizit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospitalvizitorder',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_district_vizit', to='apps_user.district'),
        ),
        migrations.AddField(
            model_name='doublevizitexcel',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_user.district'),
        ),
    ]
